"""Migration - Migration_e022d34f-937b-444d-ae94-0bfbf02f35f0

Revision ID: 00a81b278baf
Revises: 7fe2538d565c
Create Date: 2024-10-16 09:41:28.198145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '00a81b278baf'
down_revision: Union[str, None] = '7fe2538d565c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'banned_ips', ['uid'])
    op.create_unique_constraint(None, 'cards', ['uid'])
    op.create_unique_constraint(None, 'known_ips', ['uid'])
    op.create_unique_constraint(None, 'users', ['uid'])
    op.create_unique_constraint(None, 'users', ['companyName'])
    op.create_unique_constraint(None, 'verified_emails', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verified_emails', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'known_ips', type_='unique')
    op.drop_constraint(None, 'cards', type_='unique')
    op.drop_constraint(None, 'banned_ips', type_='unique')
    # ### end Alembic commands ###
