"""Initial Migration

Revision ID: 2041cc39aa60
Revises: 9d5fbc7a5031
Create Date: 2024-10-15 14:56:48.750778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2041cc39aa60'
down_revision: Union[str, None] = '9d5fbc7a5031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
