"""Migration - Migration_5b280c88-baf3-4c5f-961a-d631e7432055

Revision ID: 5468652e0c15
Revises: 7663ce877259
Create Date: 2024-10-16 19:45:21.251266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5468652e0c15'
down_revision: Union[str, None] = '7663ce877259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'analytics', ['uid'])
    op.add_column('buttons_clicked', sa.Column('createdAt', postgresql.TIMESTAMP(), nullable=False))
    op.create_unique_constraint(None, 'buttons_clicked', ['uid'])
    op.create_unique_constraint(None, 'page_views', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'page_views', type_='unique')
    op.drop_constraint(None, 'buttons_clicked', type_='unique')
    op.drop_column('buttons_clicked', 'createdAt')
    op.drop_constraint(None, 'analytics', type_='unique')
    # ### end Alembic commands ###
