"""Migration - Migration_0e920b96-c2eb-4692-8acf-22a39d4926fd

Revision ID: 7663ce877259
Revises: e13487edfc80
Create Date: 2024-10-16 15:59:18.308008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7663ce877259'
down_revision: Union[str, None] = 'e13487edfc80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'testimonials', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'testimonials', type_='unique')
    # ### end Alembic commands ###
