"""Migration - Migration_21741ba9-6b6a-4fa9-be54-a8ee40c6e06a

Revision ID: 7fe2538d565c
Revises: 34f14995beee
Create Date: 2024-10-15 19:22:35.742639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7fe2538d565c'
down_revision: Union[str, None] = '34f14995beee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
