"""Migration - Migration_b9d08dae-e571-4dbe-a0b6-cf8d4f20f73a

Revision ID: 852bbd6731f0
Revises: db3d09309f24
Create Date: 2024-10-18 02:39:26.640038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '852bbd6731f0'
down_revision: Union[str, None] = 'db3d09309f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'milestones', ['uid'])
    op.add_column('requested_services', sa.Column('totalCost', sa.Numeric(scale=2), nullable=False))
    op.create_unique_constraint(None, 'requested_services', ['uid'])
    op.create_unique_constraint(None, 'service_feature', ['uid'])
    op.create_unique_constraint(None, 'services', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='unique')
    op.drop_constraint(None, 'service_feature', type_='unique')
    op.drop_constraint(None, 'requested_services', type_='unique')
    op.drop_column('requested_services', 'totalCost')
    op.drop_constraint(None, 'milestones', type_='unique')
    # ### end Alembic commands ###
