"""Initial Migration

Revision ID: aabe1da37404
Revises: 2041cc39aa60
Create Date: 2024-10-15 15:03:40.647001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aabe1da37404'
down_revision: Union[str, None] = '2041cc39aa60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'cardNumber',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cards', 'expirationDate',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('cards', 'cvv',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'cvv',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('cards', 'expirationDate',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('cards', 'cardNumber',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
