"""Migration - Migration_53dcd927-69a9-4408-898a-53e62a15d37a

Revision ID: db3d09309f24
Revises: 5468652e0c15
Create Date: 2024-10-17 03:56:39.128197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'db3d09309f24'
down_revision: Union[str, None] = '5468652e0c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'project_images', ['uid'])
    op.create_unique_constraint(None, 'project_stacks', ['uid'])
    op.create_unique_constraint(None, 'projects', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_constraint(None, 'project_stacks', type_='unique')
    op.drop_constraint(None, 'project_images', type_='unique')
    # ### end Alembic commands ###
