"""Migration - Migration_2f9adf66-23d8-462b-bf88-336a41211ec1

Revision ID: e13487edfc80
Revises: 00a81b278baf
Create Date: 2024-10-16 14:36:47.490712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e13487edfc80'
down_revision: Union[str, None] = '00a81b278baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'faqs', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'faqs', type_='unique')
    # ### end Alembic commands ###
